CREATE OR REPLACE PROCEDURE VENCD.CLOSE_SETIMANA(V_SETTIMANA PA_CD_PIANIFICAZIONE.C_SETTIMANA)IS
BEGIN
   CLOSE V_SETTIMANA;
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       RAISE;
     WHEN OTHERS THEN
       RAISE;
END CLOSE_SETIMANA; 
/

