
CREATE OR REPLACE TYPE VENCD.PERIODO AS OBJECT
(
  ANNO NUMBER(4),
  CICLO NUMBER(2),
  PER VARCHAR2(1),
  IMPORTOLORDO NUMBER,
  IMPORTONETTO NUMBER,
  PERCSCONTO NUMBER,
  NOTA VARCHAR2(80),
  ID_PERIODO_SPECIALE NUMBER(7),
  ID_PERIODO NUMBER(7)
)
/



